#!/usr/bin/env node
/**
 * Bring the MP portraits into the repository, where the app can actually reach
 * them.
 *
 * ## Why this script exists
 *
 * Until August 2026 both surfaces pointed their `<img>` at the URL the API
 * hands out for a member's photo:
 *
 *     https://api.riigikogu.ee/api/files/<file-uuid>/download
 *
 * That URL is keyed by the *file* record, not by the member, and the CMS mints
 * a new file record whenever a portrait is re-published. On 2026-08-25, 66 of
 * the 101 URLs committed on 2026-08-12 answered `404 File not found` — two
 * thirds of the roster fell back to initials, on both surfaces, for every
 * visitor. The URLs also cannot be refreshed often enough to outrun the rot: a
 * monthly job publishes a snapshot that starts dying within days.
 *
 * Two smaller faults sit behind the same `<img src>`:
 *
 * - `api.riigikogu.ee` rate-limits per IP and answers `429` to a burst — four
 *   parallel requests are enough to draw one — while a roster paints a hundred
 *   images at once. There is no `Retry-After` to obey and no `Cache-Control`,
 *   `ETag` or `Last-Modified` on the `200`s either, so nothing is reliably
 *   cached and every visit re-runs the same burst.
 * - Being cross-origin, the portraits are invisible to the service worker
 *   (`service-worker.js` deliberately leaves other origins alone), so they
 *   never worked offline.
 *
 * So the portraits stop being a runtime dependency on someone else's server and
 * become part of the deployment: this script downloads them once, encodes each
 * to a 270px WebP (~7 KB, the size the largest avatar actually paints at
 * 2×), and commits them under `assets/mps/<uuid>.webp`. Same origin, same CDN
 * as the app, precached with everything else, and keyed by the member's uuid —
 * which does not rotate.
 *
 * ## What it writes
 *
 * | Path | What |
 * |---|---|
 * | `assets/mps/<uuid>.webp` | one portrait per member, 270×270 |
 * | `assets/mps/manifest.json` | provenance: the source URL and the sha256 of the source bytes each file was encoded from |
 * | `data/mps.json` | the `photoUrl` (upstream, refreshed) and `photo` (local path) fields, and nothing else |
 * | `service-worker.js` | the generated block of the precache list |
 *
 * It is the only writer of `photo`/`photoUrl` besides `build_data.py`, which
 * writes the whole file — see `data/README.md`, "Who writes what". It never
 * adds or removes a member: a uuid that is not already in `data/mps.json` is
 * reported and skipped, because a roster change is `build_data.py`'s to make.
 *
 * ## How it talks to the API
 *
 * One request at a time, with backoff on `429` — the burst is the thing being
 * fixed, so committing it here would be perverse. A full run is ~101 requests
 * and takes about a minute.
 *
 * Usage:
 *     node scripts/fetch_mp_photos.mjs [--check] [--data DIR]
 *
 *     --check   download nothing; verify that every member has a portrait on
 *               disk and that the precache list agrees. Exit 1 if not.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const MEMBERS_API = 'https://api.riigikogu.ee/api/plenary-members?lang=EN';

/** The portrait's edge, in CSS pixels × 2. The largest avatar paints at 128px
 *  (desktop `xl`), so 270 — which is also what the API serves — covers a 2×
 *  display without upscaling and leaves nothing to gain from a bigger file. */
const EDGE = 270;
const QUALITY = 80;

const ASSET_DIR = join(REPO, 'assets', 'mps');
/** Repo-relative, POSIX — this string is what `data/mps.json` carries. */
const assetPath = (uuid) => `assets/mps/${uuid}.webp`;

const BEGIN = '  // BEGIN MP PORTRAITS — generated by scripts/fetch_mp_photos.mjs';
const END = '  // END MP PORTRAITS';

/* ------------------------------------------------------------------ *
 * plumbing
 * ------------------------------------------------------------------ */

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const sha256 = (buffer) => createHash('sha256').update(buffer).digest('hex');

const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));
/** Written the way `build_data.py` writes JSON, so the two never fight over formatting. */
const writeJson = (path, value) => writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');

/**
 * Fetch with backoff, because the origin rate-limits and says so with a bare
 * `429` — no `Retry-After` to obey, so the schedule is ours to pick.
 */
async function get(url, { attempts = 5 } = {}) {
  let lastStatus = 0;
  for (let attempt = 0; attempt < attempts; attempt += 1) {
    let response;
    try {
      response = await fetch(url);
    } catch (cause) {
      if (attempt === attempts - 1) throw new Error(`${url}: ${cause.message}`, { cause });
      await sleep(1000 * (attempt + 1));
      continue;
    }
    if (response.ok) return Buffer.from(await response.arrayBuffer());
    lastStatus = response.status;
    // 404 is an answer, not a hiccup: the file record is gone and retrying it
    // just spends the rate limit that the next member needs.
    if (response.status !== 429 && response.status < 500) break;
    await sleep(1500 * (attempt + 1));
  }
  throw new Error(`${url}: HTTP ${lastStatus || 'no response'}`);
}

/* ------------------------------------------------------------------ *
 * the three files this script keeps in agreement
 * ------------------------------------------------------------------ */

/** The `photo`/`photoUrl` pair, written back in place — every other field untouched. */
function updateRoster(rosterPath, resolved) {
  const roster = readJson(rosterPath);
  let changed = 0;

  const updated = roster.map((mp) => {
    const record = resolved.get(mp.uuid);
    if (!record) return mp;
    if (mp.photoUrl === record.sourceUrl && mp.photo === assetPath(mp.uuid)) return mp;
    changed += 1;

    // Rebuilt key by key so `photo` lands beside `photoUrl` rather than at the
    // end of the record: this file is read by people as well as by the app.
    const next = {};
    for (const [key, value] of Object.entries(mp)) {
      next[key] = key === 'photoUrl' ? record.sourceUrl : value;
      if (key === 'photoUrl') next.photo = assetPath(mp.uuid);
    }
    return next;
  });

  if (changed > 0) writeJson(rosterPath, updated);
  return changed;
}

/**
 * The precache list's generated block.
 *
 * The list has to name every portrait explicitly for the same reason it names
 * every icon: `install` fails loudly in this worker, `tests/unit/photos.test.mjs`
 * holds the list to what is on disk, and `pwa/desktop-offline.spec.js` D5.4
 * holds it to every same-origin URL the app requests. Hand-maintaining a
 * hundred lines is not on, so this writes them.
 */
function updatePrecache(uuids) {
  const path = join(REPO, 'service-worker.js');
  const source = readFileSync(path, 'utf8');
  const start = source.indexOf(BEGIN);
  const end = source.indexOf(END);
  if (start === -1 || end === -1) {
    throw new Error('service-worker.js: the MP PORTRAITS markers are gone — restore them before running this');
  }

  const lines = uuids.map((uuid) => `  './${assetPath(uuid)}',`).join('\n');
  const next = `${source.slice(0, start)}${BEGIN}\n${lines}\n${source.slice(end)}`;
  if (next === source) return false;
  writeFileSync(path, next, 'utf8');
  return true;
}

/** Files under `assets/mps/` that no member claims any more. */
function prune(uuids) {
  const wanted = new Set(uuids.map((uuid) => `${uuid}.webp`));
  const orphans = readdirSync(ASSET_DIR).filter(
    (name) => name.endsWith('.webp') && !wanted.has(name),
  );
  for (const name of orphans) rmSync(join(ASSET_DIR, name));
  return orphans;
}

/* ------------------------------------------------------------------ *
 * --check
 * ------------------------------------------------------------------ */

function check(rosterPath) {
  const roster = readJson(rosterPath);
  const problems = [];

  for (const mp of roster) {
    if (!mp.photo) {
      problems.push(`${mp.name}: no "photo" field`);
      continue;
    }
    if (mp.photo !== assetPath(mp.uuid)) {
      problems.push(`${mp.name}: photo is ${mp.photo}, expected ${assetPath(mp.uuid)}`);
    }
    if (!existsSync(join(REPO, mp.photo))) problems.push(`${mp.name}: ${mp.photo} is not on disk`);
  }

  const listed = [...readFileSync(join(REPO, 'service-worker.js'), 'utf8')
    .matchAll(/'\.\/(assets\/mps\/[^']+)'/g)].map((match) => match[1]);
  const wanted = roster.filter((mp) => mp.photo).map((mp) => mp.photo);
  const missing = wanted.filter((path) => !listed.includes(path));
  const extra = listed.filter((path) => !wanted.includes(path));
  if (missing.length) problems.push(`precache list is missing ${missing.length} portrait(s)`);
  if (extra.length) problems.push(`precache list names ${extra.length} portrait(s) no member claims`);

  if (problems.length) {
    console.error(`FAIL — ${problems.length} problem(s):`);
    for (const problem of problems) console.error(`  - ${problem}`);
    return 1;
  }
  console.log(`OK — ${roster.length} members, ${wanted.length} portraits, precache list agrees.`);
  return 0;
}

/* ------------------------------------------------------------------ *
 * main
 * ------------------------------------------------------------------ */

async function main(argv) {
  const dataDir = argv.includes('--data') ? argv[argv.indexOf('--data') + 1] : join(REPO, 'data');
  const rosterPath = join(dataDir, 'mps.json');

  if (argv.includes('--check')) return check(rosterPath);

  mkdirSync(ASSET_DIR, { recursive: true });
  const roster = readJson(rosterPath);
  const known = new Map(roster.map((mp) => [mp.uuid, mp]));

  // The live list, not the committed one: the committed `photoUrl` is a
  // snapshot of a rotating identifier and is stale more often than not. It is
  // still the fallback, for the member the API somehow does not return.
  console.log(`Fetching ${MEMBERS_API} …`);
  const live = JSON.parse((await get(MEMBERS_API)).toString('utf8'));

  const previous = existsSync(join(ASSET_DIR, 'manifest.json'))
    ? new Map(readJson(join(ASSET_DIR, 'manifest.json')).portraits.map((p) => [p.uuid, p]))
    : new Map();

  const resolved = new Map();
  const failures = [];
  let downloaded = 0;
  let unchanged = 0;
  let strangers = 0;

  for (const member of live) {
    const uuid = member.uuid;
    const mp = known.get(uuid);
    if (!mp) {
      // A roster change the API has and `data/mps.json` does not. Reporting it
      // is right; acting on it is `build_data.py`'s job, not this script's.
      console.warn(`  ! ${member.fullName}: not in data/mps.json — run build_data.py`);
      strangers += 1;
      continue;
    }

    const sourceUrl = member.photo?._links?.download?.href ?? mp.photoUrl ?? null;
    if (!sourceUrl) {
      failures.push(`${mp.name}: the API publishes no portrait`);
      continue;
    }

    let source;
    try {
      source = await get(sourceUrl);
    } catch (error) {
      failures.push(`${mp.name}: ${error.message}`);
      continue;
    }

    const hash = sha256(source);
    const file = join(ASSET_DIR, `${uuid}.webp`);
    const before = previous.get(uuid);

    // Re-encoding identical bytes produces an identical file, but writing it
    // anyway would churn the repository every month for nothing.
    if (before?.sourceSha256 === hash && existsSync(file)) {
      resolved.set(uuid, { ...before, sourceUrl });
      unchanged += 1;
    } else {
      const webp = await sharp(source)
        .resize(EDGE, EDGE, { fit: 'cover', position: 'top' })
        .webp({ quality: QUALITY })
        .toBuffer();
      writeFileSync(file, webp);
      resolved.set(uuid, {
        uuid,
        name: mp.name,
        file: assetPath(uuid),
        bytes: webp.length,
        sourceUrl,
        sourceSha256: hash,
      });
      downloaded += 1;
      console.log(`  + ${mp.name} (${(webp.length / 1024).toFixed(1)} KB)`);
    }

    await sleep(120);
  }

  if (failures.length > 0) {
    // Publishing a roster where some members have no portrait on disk would
    // make `install` fail for every visitor, so this is fatal rather than a
    // warning — the previous portraits stay committed and the app keeps working.
    console.error(`\nFAIL — ${failures.length} portrait(s) could not be fetched:`);
    for (const failure of failures) console.error(`  - ${failure}`);
    return 1;
  }

  const uuids = [...resolved.keys()].sort();
  const orphans = prune(uuids);
  const rosterChanges = updateRoster(rosterPath, resolved);

  const portraits = uuids.map((uuid) => resolved.get(uuid));
  const manifestPath = join(ASSET_DIR, 'manifest.json');
  const before = existsSync(manifestPath) ? readJson(manifestPath) : null;
  const same = before && JSON.stringify(before.portraits) === JSON.stringify(portraits);
  if (!same) {
    writeJson(manifestPath, {
      source: MEMBERS_API,
      fetchedAt: new Date().toISOString().slice(0, 10),
      edge: EDGE,
      quality: QUALITY,
      portraits,
    });
  }

  const precacheChanged = updatePrecache(uuids);

  console.log(
    `\n${downloaded} written, ${unchanged} unchanged, ${orphans.length} pruned, `
    + `${rosterChanges} roster record(s) updated.`,
  );
  if (strangers > 0) console.log(`${strangers} member(s) the roster does not know — run build_data.py.`);
  if (precacheChanged) {
    console.log(
      'The precache list changed — bump CACHE_NAME in service-worker.js so returning\n'
      + 'visitors are not served the old cache.',
    );
  }
  return 0;
}

process.exit(await main(process.argv.slice(2)));
